version: "3.8"
services:
  #nginx
  webserver:
    image: nginx:latest
    container_name: ads_nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/dockerfiles
      - ./ads_app:/var/www/html
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dockerfiles/nginx/error_log:/etc/nginx/error_log
      - ./dockerfiles/nginx/access_log:/etc/nginx/access_log
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    networks:
      - amydressshop

  #mysql
  mysql:
    image: mysql:8.3.0
    container_name: ads_mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: 'ads_data'
      MYSQL_USER: 'ads_user'
      MYSQL_PASS: 'ads_pw'
      MYSQL_ROOT_PASSWORD: 'ads_pw'
    ports:
      - "3306:3306"
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql
      - ./dockerfiles/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - amydressshop
  #php
  php:
    build:
      dockerfile: ./dockerfiles/php/php.dockerfile
    container_name: ads_php
    volumes:
      - .:/var/www/dockerfiles
      - ./ads_app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - amydressshop

  composer:
    image: composer:latest
    container_name: ads_composer
    volumes:
      - .:/var/www/dockerfiles
      - ./ads_app:/var/www/html
    working_dir: /var/www/html
    networks:
      - amydressshop

  #npm
  npm:
    image: node:21-alpine3.18
    container_name: ads_node
    volumes:
      - .:/var/www/dockerfiles
      - ./ads_app:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/php/php.dockerfile
    container_name: ads_artisan
    volumes:
      - .:/var/www/dockerfiles
      - ./ads_app:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']

networks:
  amydressshop:
